---
version: "2.0"
services:
  cjdns:
    image: pkteer/pkt-server-akash
    expose:
      - port: 64764
        as: 64764
        proto: tcp
        to:
          - global: true
      - port: 28665
        as: 28665
        to:
          - global: true
    env:
      - AKASH=true
    params:
      storage:
        data:
          mount: /pkt-server/vpn_data
          readOnly: false
profiles:
  compute:
    cjdns:
      resources:
        cpu:
          units: 2
        memory:
          size: 2048Mi
        storage:
          - size: 10GB
          - name: data
            size: 1GB
            attributes:
              persistent: true
              class: beta3
  placement:
    dcloud:
      pricing:
        cjdns:
          denom: uakt
          amount: 1000
deployment:
  cjdns:
    dcloud:
      profile: cjdns
      count: 1
